FROM quay.io/pypa/manylinux2014_aarch64:latest

RUN yum update -y \
  && yum install -y wget \
  && yum clean all
  
RUN mkdir /tmp/dl \
    && cd /tmp/dl \
    && wget https://cmake.org/files/v3.13/cmake-3.13.3.tar.gz \
    && tar -zxvf cmake-3.13.3.tar.gz \
    && cd cmake-3.13.3 && ./bootstrap --prefix=/usr/local && make && make install \
    && export PATH=/usr/local/bin:$PATH:/opt/python/cp37-cp37m/bin/

ENV CC=gcc
ENV CXX=g++
ENV CXXFLAGS=-static-libstdc++

COPY . /src
WORKDIR /src
