FROM quay.io/pypa/manylinux2014_aarch64:latest

RUN yum update -y \
  && yum install -y wget\
  && yum clean all

RUN yum install -y epel-release \
  && yum install -y jsoncpp cmake3 \
  && ln -sf /usr/bin/cmake3 /usr/bin/cmake

ENV PATH=$PATH:/opt/python/cp37-cp37m/bin/

ENV CC=gcc
ENV CXX=g++
ENV CXXFLAGS=-static-libstdc++

COPY . /src
WORKDIR /src
